{% set version = "1.0.4" %} # Remember to update sha256 below

package:
  name: biophi
  version: '{{ version }}'

source:
  url: https://github.com/Merck/BioPhi/archive/v{{ version }}.tar.gz
  sha256: '11f6758b99bf23dfc64c312082cd5cdd2080eb24'

build:
  noarch: python
  number: 0
  entry_points:
    - biophi = biophi.common.cli.main:main
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - pytest
  run:
    - python >=3.8
    - abnumber ==0.2.7
    - anarci ==2020.04.23
    - hmmer >=3.1
    - click >=7
    - pandas
    - sqlalchemy
    - flask
    - redis
    - celery
    - biopython
    - requests
    - tqdm
    - xlsxwriter
    - humanize
    - sapiens

test:
  imports:
    - biophi
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - biophi --help
    - biophi sapiens --help
    - biophi oasis --help
    - pytest tests

about:
  home: https://github.com/Merck/BioPhi
  license: MIT
  license_family: MIT
  summary: BioPhi open-source antibody design platform
